// <auto-generated />
using System;
using FMFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FMFlow.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421193510_Estimates")]
    partial class Estimates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:AutoMigrationsEnabled", false)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeUserZipCode", b =>
                {
                    b.Property<string>("AssignedZipCodesZipcode")
                        .HasColumnType("text");

                    b.Property<int>("EmployeesAssignedUserID")
                        .HasColumnType("integer");

                    b.HasKey("AssignedZipCodesZipcode", "EmployeesAssignedUserID");

                    b.HasIndex("EmployeesAssignedUserID");

                    b.ToTable("EmployeeUserZipCode");
                });

            modelBuilder.Entity("FMFlow.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line2")
                        .HasColumnType("text");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressID");

                    b.HasIndex("StateId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FMFlow.Entities.Billing", b =>
                {
                    b.Property<int>("BillingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillingID"));

                    b.Property<int?>("BillingPlanID")
                        .HasColumnType("integer");

                    b.Property<long?>("CardID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContractID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MerchantID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultedCardToken")
                        .HasColumnType("text");

                    b.HasKey("BillingID");

                    b.HasIndex("BillingPlanID");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("FMFlow.Entities.BillingPlan", b =>
                {
                    b.Property<int>("BillingPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillingPlanID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BillingFrequency")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("BillingPlanID");

                    b.ToTable("BillingPlans");
                });

            modelBuilder.Entity("FMFlow.Entities.EmployeeUser", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<decimal?>("BurdenRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyGoal")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("TwilioCallerID")
                        .HasColumnType("text");

                    b.Property<string>("TwilioNumber")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("EmployeeUsers");
                });

            modelBuilder.Entity("FMFlow.Entities.Estimate", b =>
                {
                    b.Property<int>("EstimateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstimateID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProUserID")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.HasKey("EstimateID");

                    b.HasIndex("ProUserID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Estimates");
                });

            modelBuilder.Entity("FMFlow.Entities.FMTimeZone", b =>
                {
                    b.Property<int>("TimeZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeZoneId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TimeZoneId");

                    b.ToTable("FMTimeZones");
                });

            modelBuilder.Entity("FMFlow.Entities.FlowUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("FMFlowUsers");
                });

            modelBuilder.Entity("FMFlow.Entities.Lead", b =>
                {
                    b.Property<int>("LeadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LeadSourceID")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ProUserID")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeadID");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("ProUserID");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("FMFlow.Entities.LeadSource", b =>
                {
                    b.Property<int>("LeadSourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadSourceID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeadSourceID");

                    b.ToTable("LeadSources");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserDetail", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("AddressOfStore")
                        .HasColumnType("text");

                    b.Property<int?>("BillingID")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FMTimeZoneID")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleReview")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfEmployees")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OnboardingFormStop")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("RequestedReferrals")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Services")
                        .HasColumnType("text[]");

                    b.Property<string>("SizeOfJob")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YelpReview")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCodeOfStore")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("BillingID");

                    b.HasIndex("FMTimeZoneID");

                    b.ToTable("ProUserDetails");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserToProZipcode", b =>
                {
                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Zipcode", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ProUserToProZipcodes");
                });

            modelBuilder.Entity("FMFlow.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FMFlow.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("LeadID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("ProjectID");

                    b.HasIndex("AddressID");

                    b.HasIndex("LeadID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FMFlow.Entities.Sheen", b =>
                {
                    b.Property<int>("SheenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SheenID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SheenID");

                    b.ToTable("Sheens");
                });

            modelBuilder.Entity("FMFlow.Entities.State", b =>
                {
                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Abbreviation");

                    b.ToTable("States");
                });

            modelBuilder.Entity("FMFlow.Entities.ZipCode", b =>
                {
                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateAbbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Zipcode");

                    b.HasIndex("StateAbbreviation");

                    b.ToTable("ZipCodes");
                });

            modelBuilder.Entity("EmployeeUserZipCode", b =>
                {
                    b.HasOne("FMFlow.Entities.ZipCode", null)
                        .WithMany()
                        .HasForeignKey("AssignedZipCodesZipcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.EmployeeUser", null)
                        .WithMany()
                        .HasForeignKey("EmployeesAssignedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FMFlow.Entities.Address", b =>
                {
                    b.HasOne("FMFlow.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("FMFlow.Entities.Billing", b =>
                {
                    b.HasOne("FMFlow.Entities.BillingPlan", "BillingPlan")
                        .WithMany()
                        .HasForeignKey("BillingPlanID");

                    b.Navigation("BillingPlan");
                });

            modelBuilder.Entity("FMFlow.Entities.EmployeeUser", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "FlowUser")
                        .WithOne("EmployeeUser")
                        .HasForeignKey("FMFlow.Entities.EmployeeUser", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowUser");
                });

            modelBuilder.Entity("FMFlow.Entities.Estimate", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserID");

                    b.HasOne("FMFlow.Entities.Project", "Project")
                        .WithMany("Estimates")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FMFlow.Entities.Lead", b =>
                {
                    b.HasOne("FMFlow.Entities.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID");

                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserID");

                    b.Navigation("LeadSource");

                    b.Navigation("ProUser");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserDetail", b =>
                {
                    b.HasOne("FMFlow.Entities.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingID");

                    b.HasOne("FMFlow.Entities.FMTimeZone", "FMTimeZone")
                        .WithMany()
                        .HasForeignKey("FMTimeZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "FlowUser")
                        .WithOne("ProUser")
                        .HasForeignKey("FMFlow.Entities.ProUserDetail", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("FMTimeZone");

                    b.Navigation("FlowUser");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserToProZipcode", b =>
                {
                    b.HasOne("FMFlow.Entities.ProUserDetail", "ProUserDetail")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.ZipCode", "ProZipcode")
                        .WithMany()
                        .HasForeignKey("Zipcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUserDetail");

                    b.Navigation("ProZipcode");
                });

            modelBuilder.Entity("FMFlow.Entities.Project", b =>
                {
                    b.HasOne("FMFlow.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("FMFlow.Entities.ZipCode", b =>
                {
                    b.HasOne("FMFlow.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateAbbreviation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("FMFlow.Entities.FlowUser", b =>
                {
                    b.Navigation("EmployeeUser");

                    b.Navigation("ProUser");
                });

            modelBuilder.Entity("FMFlow.Entities.Project", b =>
                {
                    b.Navigation("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
