// <auto-generated />
using System;
using FMFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FMFlow.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401145251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:AutoMigrationsEnabled", false)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FMFlow.Entities.Billing", b =>
                {
                    b.Property<int>("BillingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillingID"));

                    b.Property<int?>("BillingPlanID")
                        .HasColumnType("integer");

                    b.Property<long?>("CardID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContractID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MerchantID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultedCardToken")
                        .HasColumnType("text");

                    b.HasKey("BillingID");

                    b.HasIndex("BillingPlanID");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("FMFlow.Entities.BillingPlan", b =>
                {
                    b.Property<int>("BillingPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillingPlanID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BillingFrequency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("BillingPlanID");

                    b.ToTable("BillingPlans");
                });

            modelBuilder.Entity("FMFlow.Entities.EmployeeUser", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<decimal?>("BurdenRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyGoal")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("TwilioCallerID")
                        .HasColumnType("text");

                    b.Property<string>("TwilioNumber")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("EmployeeUsers");
                });

            modelBuilder.Entity("FMFlow.Entities.FMTimeZone", b =>
                {
                    b.Property<int>("TimeZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeZoneId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TimeZoneId");

                    b.ToTable("TimeZones");
                });

            modelBuilder.Entity("FMFlow.Entities.FlowUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("FMFlowUser");
                });

            modelBuilder.Entity("FMFlow.Entities.Lead", b =>
                {
                    b.Property<int>("LeadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LeadSourceID")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeadID");

                    b.HasIndex("LeadSourceID");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("FMFlow.Entities.LeadSource", b =>
                {
                    b.Property<int>("LeadSourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadSourceID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeadSourceID");

                    b.ToTable("LeadSource");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserDetail", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("AccountManagerUserID")
                        .HasColumnType("integer");

                    b.Property<string>("AddressOfStore")
                        .HasColumnType("text");

                    b.Property<int?>("BillingID")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CardID")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ContractID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FMTimeZoneID")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleReview")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfEmployees")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OnboardingFormStop")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("RequestedReferrals")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Services")
                        .HasColumnType("text[]");

                    b.Property<string>("SizeOfJob")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YelpReview")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCodeOfStore")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("AccountManagerUserID");

                    b.HasIndex("BillingID");

                    b.HasIndex("FMTimeZoneID");

                    b.ToTable("ProUserDetail");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserToProZipcode", b =>
                {
                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Zipcode", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ProUserToProZipcode");
                });

            modelBuilder.Entity("FMFlow.Entities.ProZipcode", b =>
                {
                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateAbbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Zipcode");

                    b.HasIndex("StateAbbreviation");

                    b.ToTable("ProZipcode");
                });

            modelBuilder.Entity("FMFlow.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("FMFlow.Entities.Sheen", b =>
                {
                    b.Property<int>("SheenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SheenID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SheenID");

                    b.ToTable("Sheen");
                });

            modelBuilder.Entity("FMFlow.Entities.State", b =>
                {
                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Abbreviation");

                    b.ToTable("State");
                });

            modelBuilder.Entity("FMFlow.Entities.Billing", b =>
                {
                    b.HasOne("FMFlow.Entities.BillingPlan", "BillingPlan")
                        .WithMany()
                        .HasForeignKey("BillingPlanID");

                    b.Navigation("BillingPlan");
                });

            modelBuilder.Entity("FMFlow.Entities.EmployeeUser", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "FlowUser")
                        .WithOne("EmployeeUser")
                        .HasForeignKey("FMFlow.Entities.EmployeeUser", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowUser");
                });

            modelBuilder.Entity("FMFlow.Entities.Lead", b =>
                {
                    b.HasOne("FMFlow.Entities.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID");

                    b.Navigation("LeadSource");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserDetail", b =>
                {
                    b.HasOne("FMFlow.Entities.EmployeeUser", "AccountManager")
                        .WithMany()
                        .HasForeignKey("AccountManagerUserID");

                    b.HasOne("FMFlow.Entities.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingID");

                    b.HasOne("FMFlow.Entities.FMTimeZone", "FMTimeZone")
                        .WithMany()
                        .HasForeignKey("FMTimeZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "FlowUser")
                        .WithOne("ProUser")
                        .HasForeignKey("FMFlow.Entities.ProUserDetail", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountManager");

                    b.Navigation("Billing");

                    b.Navigation("FMTimeZone");

                    b.Navigation("FlowUser");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserToProZipcode", b =>
                {
                    b.HasOne("FMFlow.Entities.ProUserDetail", "ProUserDetail")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.ProZipcode", "ProZipcode")
                        .WithMany()
                        .HasForeignKey("Zipcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUserDetail");

                    b.Navigation("ProZipcode");
                });

            modelBuilder.Entity("FMFlow.Entities.ProZipcode", b =>
                {
                    b.HasOne("FMFlow.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateAbbreviation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("FMFlow.Entities.FlowUser", b =>
                {
                    b.Navigation("EmployeeUser");

                    b.Navigation("ProUser");
                });
#pragma warning restore 612, 618
        }
    }
}
