// <auto-generated />
using System;
using System.Text.Json;
using FMFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FMFlow.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828163252_MxCustomerId")]
    partial class MxCustomerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:AutoMigrationsEnabled", false)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeUserZipCode", b =>
                {
                    b.Property<string>("AssignedZipCodesZipcode")
                        .HasColumnType("text");

                    b.Property<int>("EmployeesAssignedUserID")
                        .HasColumnType("integer");

                    b.HasKey("AssignedZipCodesZipcode", "EmployeesAssignedUserID");

                    b.HasIndex("EmployeesAssignedUserID");

                    b.ToTable("EmployeeUserZipCode");
                });

            modelBuilder.Entity("FMFlow.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line2")
                        .HasColumnType("text");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressID");

                    b.HasIndex("StateId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FMFlow.Entities.Billing", b =>
                {
                    b.Property<int>("BillingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillingID"));

                    b.Property<int?>("BillingPlanID")
                        .HasColumnType("integer");

                    b.Property<long?>("CardID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContractID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MerchantID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultedCardToken")
                        .HasColumnType("text");

                    b.HasKey("BillingID");

                    b.HasIndex("BillingPlanID");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("FMFlow.Entities.BillingPlan", b =>
                {
                    b.Property<int>("BillingPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillingPlanID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BillingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("BillingPlanID");

                    b.ToTable("BillingPlans");
                });

            modelBuilder.Entity("FMFlow.Entities.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("ColorType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("FinesWhitesAndNeutrals")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaintAreaType")
                        .HasColumnType("text");

                    b.Property<int?>("PictureFileId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryFamily")
                        .HasColumnType("text");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("SWColorId")
                        .HasColumnType("text");

                    b.Property<string>("SherwinWilliamsPictureURL")
                        .HasColumnType("text");

                    b.Property<string>("TintCategory")
                        .HasColumnType("text");

                    b.Property<int?>("Top50Exterior")
                        .HasColumnType("integer");

                    b.Property<int?>("Top50Interior")
                        .HasColumnType("integer");

                    b.HasKey("ColorId");

                    b.HasIndex("PictureFileId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SWColorId")
                        .IsUnique();

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("FMFlow.Entities.CustomerTempPro", b =>
                {
                    b.Property<int>("CustomerTempProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerTempProId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpireDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProId")
                        .HasColumnType("integer");

                    b.HasKey("CustomerTempProId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProId");

                    b.ToTable("CustomerTempPros");
                });

            modelBuilder.Entity("FMFlow.Entities.EmployeeUser", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<decimal?>("BurdenRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyGoal")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("TwilioCallerID")
                        .HasColumnType("text");

                    b.Property<string>("TwilioNumber")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("AddressID");

                    b.ToTable("EmployeeUsers");
                });

            modelBuilder.Entity("FMFlow.Entities.Estimate", b =>
                {
                    b.Property<int>("EstimateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstimateID"));

                    b.Property<JsonDocument>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("CalculationResults")
                        .HasColumnType("jsonb");

                    b.Property<bool>("DepositHasBeenPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeenPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("boolean");

                    b.Property<int?>("JobId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("ProUserID")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedEstimateID")
                        .HasColumnType("integer");

                    b.Property<int?>("ScheduledEstimateID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StatusLastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("EstimateID");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("ProUserID");

                    b.HasIndex("RequestedEstimateID");

                    b.HasIndex("ScheduledEstimateID");

                    b.ToTable("Estimates");
                });

            modelBuilder.Entity("FMFlow.Entities.EstimateNote", b =>
                {
                    b.Property<int>("EstimateNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstimateNoteId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EstimateNoteId");

                    b.HasIndex("EstimateId");

                    b.ToTable("EstimateNotes");
                });

            modelBuilder.Entity("FMFlow.Entities.FMTimeZone", b =>
                {
                    b.Property<int>("TimeZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeZoneId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TimeZoneId");

                    b.ToTable("FMTimeZones");
                });

            modelBuilder.Entity("FMFlow.Entities.FileItem", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileID"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileID");

                    b.ToTable("FileItems");
                });

            modelBuilder.Entity("FMFlow.Entities.FileItemToEstimate", b =>
                {
                    b.Property<int>("FileID")
                        .HasColumnType("integer");

                    b.Property<int>("EstimateID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ThumbnailFileID")
                        .HasColumnType("integer");

                    b.HasKey("FileID", "EstimateID");

                    b.HasIndex("EstimateID");

                    b.HasIndex("ThumbnailFileID");

                    b.ToTable("FileToEstimates");
                });

            modelBuilder.Entity("FMFlow.Entities.FlowUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("MxCustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("FMFlowUsers");
                });

            modelBuilder.Entity("FMFlow.Entities.Integration", b =>
                {
                    b.Property<int>("IntegrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntegrationID"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntegrationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("IntegrationID");

                    b.HasIndex("UserID");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("FMFlow.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<DateOnly?>("ActualDateWorkCompleted")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ActualDateWorkStarted")
                        .HasColumnType("date");

                    b.Property<bool?>("CleanedUpWorkAreas")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CompletedScopeOfWork")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ContractorWorkIsSatisfactory")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CooperativeWithCustomer")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("boolean");

                    b.Property<bool?>("NotifiedPriorToArrival")
                        .HasColumnType("boolean");

                    b.Property<string>("RateContractorPerformance")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ScheduledDateWorkCompleted")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ScheduledDateWorkStarted")
                        .HasColumnType("date");

                    b.Property<string>("SignOffComment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SignOffDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StatusLastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("FMFlow.Entities.JobNote", b =>
                {
                    b.Property<int>("JobNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobNoteId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobNoteId");

                    b.HasIndex("JobId");

                    b.ToTable("JobNotes");
                });

            modelBuilder.Entity("FMFlow.Entities.Lead", b =>
                {
                    b.Property<int>("LeadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadID"));

                    b.Property<string>("AccountCreationNonce")
                        .HasColumnType("text");

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<bool>("CanSetScheduleComplete")
                        .HasColumnType("boolean");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LeadSourceID")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NonceExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ProUserID")
                        .HasColumnType("integer");

                    b.Property<bool>("ScheduleComplete")
                        .HasColumnType("boolean");

                    b.Property<int?>("SchedulerId")
                        .HasColumnType("integer");

                    b.HasKey("LeadID");

                    b.HasIndex("AddressID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("LeadSourceID");

                    b.HasIndex("ProUserID");

                    b.HasIndex("SchedulerId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("FMFlow.Entities.LeadNote", b =>
                {
                    b.Property<int>("LeadNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadNoteId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProId")
                        .HasColumnType("integer");

                    b.HasKey("LeadNoteId");

                    b.HasIndex("LeadId");

                    b.HasIndex("ProId");

                    b.ToTable("LeadNotes");
                });

            modelBuilder.Entity("FMFlow.Entities.LeadSource", b =>
                {
                    b.Property<int>("LeadSourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadSourceID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeadSourceID");

                    b.ToTable("LeadSources");
                });

            modelBuilder.Entity("FMFlow.Entities.LeadTimeline", b =>
                {
                    b.Property<int>("TimelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimelineId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventNameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TimelineId");

                    b.HasIndex("LeadId");

                    b.HasIndex("UserId");

                    b.ToTable("LeadTimelines");
                });

            modelBuilder.Entity("FMFlow.Entities.PaintPrice", b =>
                {
                    b.Property<int>("PaintPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaintPriceId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PaintSheenId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerGallon")
                        .HasColumnType("numeric");

                    b.Property<int>("ProUserId")
                        .HasColumnType("integer");

                    b.HasKey("PaintPriceId");

                    b.HasIndex("PaintSheenId");

                    b.HasIndex("ProUserId");

                    b.ToTable("PaintPrices");
                });

            modelBuilder.Entity("FMFlow.Entities.PaintSheen", b =>
                {
                    b.Property<int>("PaintSheenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaintSheenId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SheenId")
                        .HasColumnType("integer");

                    b.HasKey("PaintSheenId");

                    b.HasIndex("ProUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SheenId");

                    b.ToTable("PaintSheens");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserDetail", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("AddressOfStore")
                        .HasColumnType("text");

                    b.Property<int?>("BillingID")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateAssignedToRsLead")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FMTimeZoneID")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleReview")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("InsuranceExpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfEmployees")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OnboardingFormStop")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("RequestedReferrals")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Services")
                        .HasColumnType("text[]");

                    b.Property<string>("SizeOfJob")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YelpReview")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCodeOfStore")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("BillingID");

                    b.HasIndex("FMTimeZoneID");

                    b.ToTable("ProUserDetails");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserFile", b =>
                {
                    b.Property<int>("ProUserFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProUserFileID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileID")
                        .HasColumnType("integer");

                    b.Property<string>("ProFileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ThumbnailFileID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ProUserFileID");

                    b.HasIndex("FileID");

                    b.HasIndex("ThumbnailFileID");

                    b.HasIndex("UserID");

                    b.ToTable("ProUserFiles");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserToProZipcode", b =>
                {
                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Zipcode", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ProUserToProZipcodes");
                });

            modelBuilder.Entity("FMFlow.Entities.ProWeekDayAvailability", b =>
                {
                    b.Property<int>("ProWeekDayAvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProWeekDayAvailabilityID"));

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ProUserID")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("ProWeekDayAvailabilityID");

                    b.HasIndex("ProUserID");

                    b.ToTable("ProWeekDayAvailabilities");
                });

            modelBuilder.Entity("FMFlow.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Cleanup")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketingCopy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaintAreaType")
                        .HasColumnType("text");

                    b.Property<int?>("PictureFileId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("text");

                    b.Property<string>("ProductLineId")
                        .HasColumnType("text");

                    b.Property<string>("SherwinWilliamsPictureURL")
                        .HasColumnType("text");

                    b.Property<string>("Substrate")
                        .HasColumnType("text");

                    b.Property<string>("SurfacePreparation")
                        .HasColumnType("text");

                    b.Property<string>("TintCategory")
                        .HasColumnType("text");

                    b.Property<string>("Warranty")
                        .HasColumnType("text");

                    b.HasKey("ProductID");

                    b.HasIndex("PictureFileId");

                    b.HasIndex("ProUserId");

                    b.HasIndex("ProductLineId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FMFlow.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("LeadID")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectID");

                    b.HasIndex("AddressID");

                    b.HasIndex("LeadID");

                    b.HasIndex("ProjectTypeID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FMFlow.Entities.ProjectNote", b =>
                {
                    b.Property<int>("ProjectNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectNoteId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectNoteId");

                    b.HasIndex("ProId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectNotes");
                });

            modelBuilder.Entity("FMFlow.Entities.ProjectType", b =>
                {
                    b.Property<int>("ProjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectTypeID"));

                    b.Property<string>("ProjectTypeAbbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectTypeID");

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("FMFlow.Entities.RequestedEstimate", b =>
                {
                    b.Property<int>("RequestedEstimateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestedEstimateID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsChangeOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProUserID")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.HasKey("RequestedEstimateID");

                    b.HasIndex("ProUserID");

                    b.HasIndex("ProjectID");

                    b.ToTable("RequestedEstimates");
                });

            modelBuilder.Entity("FMFlow.Entities.ScheduledEstimate", b =>
                {
                    b.Property<int>("ScheduledEstimateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduledEstimateID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProUserID")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduledEstimateID");

                    b.HasIndex("ProUserID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ScheduledEstimates");
                });

            modelBuilder.Entity("FMFlow.Entities.Sheen", b =>
                {
                    b.Property<int>("SheenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SheenID"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SheenID");

                    b.ToTable("Sheens");
                });

            modelBuilder.Entity("FMFlow.Entities.State", b =>
                {
                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Abbreviation");

                    b.ToTable("States");
                });

            modelBuilder.Entity("FMFlow.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EstimateId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionID");

                    b.HasIndex("EstimateId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FMFlow.Entities.ZipCode", b =>
                {
                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateAbbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Zipcode");

                    b.HasIndex("StateAbbreviation");

                    b.ToTable("ZipCodes");
                });

            modelBuilder.Entity("EmployeeUserZipCode", b =>
                {
                    b.HasOne("FMFlow.Entities.ZipCode", null)
                        .WithMany()
                        .HasForeignKey("AssignedZipCodesZipcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.EmployeeUser", null)
                        .WithMany()
                        .HasForeignKey("EmployeesAssignedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FMFlow.Entities.Address", b =>
                {
                    b.HasOne("FMFlow.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("FMFlow.Entities.Billing", b =>
                {
                    b.HasOne("FMFlow.Entities.BillingPlan", "BillingPlan")
                        .WithMany()
                        .HasForeignKey("BillingPlanID");

                    b.Navigation("BillingPlan");
                });

            modelBuilder.Entity("FMFlow.Entities.Color", b =>
                {
                    b.HasOne("FMFlow.Entities.FileItem", "PictureFile")
                        .WithMany()
                        .HasForeignKey("PictureFileId");

                    b.HasOne("FMFlow.Entities.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId");

                    b.Navigation("PictureFile");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FMFlow.Entities.CustomerTempPro", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "Pro")
                        .WithMany()
                        .HasForeignKey("ProId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Pro");
                });

            modelBuilder.Entity("FMFlow.Entities.EmployeeUser", b =>
                {
                    b.HasOne("FMFlow.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "FlowUser")
                        .WithOne("EmployeeUser")
                        .HasForeignKey("FMFlow.Entities.EmployeeUser", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("FlowUser");
                });

            modelBuilder.Entity("FMFlow.Entities.Estimate", b =>
                {
                    b.HasOne("FMFlow.Entities.Job", "Job")
                        .WithOne("Estimate")
                        .HasForeignKey("FMFlow.Entities.Estimate", "JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.RequestedEstimate", "RequestedEstimate")
                        .WithMany("Estimates")
                        .HasForeignKey("RequestedEstimateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.ScheduledEstimate", "ScheduledEstimate")
                        .WithMany("Estimates")
                        .HasForeignKey("ScheduledEstimateID");

                    b.Navigation("Job");

                    b.Navigation("ProUser");

                    b.Navigation("RequestedEstimate");

                    b.Navigation("ScheduledEstimate");
                });

            modelBuilder.Entity("FMFlow.Entities.EstimateNote", b =>
                {
                    b.HasOne("FMFlow.Entities.Estimate", "Estimate")
                        .WithMany()
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("FMFlow.Entities.FileItemToEstimate", b =>
                {
                    b.HasOne("FMFlow.Entities.Estimate", "Estimate")
                        .WithMany()
                        .HasForeignKey("EstimateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FileItem", "File")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FileItem", "ThumbnailFile")
                        .WithMany()
                        .HasForeignKey("ThumbnailFileID");

                    b.Navigation("Estimate");

                    b.Navigation("File");

                    b.Navigation("ThumbnailFile");
                });

            modelBuilder.Entity("FMFlow.Entities.Integration", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMFlow.Entities.JobNote", b =>
                {
                    b.HasOne("FMFlow.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FMFlow.Entities.Lead", b =>
                {
                    b.HasOne("FMFlow.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("FMFlow.Entities.LeadSource", "LeadSource")
                        .WithMany()
                        .HasForeignKey("LeadSourceID");

                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserID");

                    b.HasOne("FMFlow.Entities.FlowUser", "Scheduler")
                        .WithMany()
                        .HasForeignKey("SchedulerId");

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("LeadSource");

                    b.Navigation("ProUser");

                    b.Navigation("Scheduler");
                });

            modelBuilder.Entity("FMFlow.Entities.LeadNote", b =>
                {
                    b.HasOne("FMFlow.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.ProUserDetail", "Pro")
                        .WithMany()
                        .HasForeignKey("ProId");

                    b.Navigation("Lead");

                    b.Navigation("Pro");
                });

            modelBuilder.Entity("FMFlow.Entities.LeadTimeline", b =>
                {
                    b.HasOne("FMFlow.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMFlow.Entities.PaintPrice", b =>
                {
                    b.HasOne("FMFlow.Entities.PaintSheen", "PaintSheen")
                        .WithMany()
                        .HasForeignKey("PaintSheenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaintSheen");

                    b.Navigation("ProUser");
                });

            modelBuilder.Entity("FMFlow.Entities.PaintSheen", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserId");

                    b.HasOne("FMFlow.Entities.Product", "Product")
                        .WithMany("PaintSheens")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.Sheen", "Sheen")
                        .WithMany()
                        .HasForeignKey("SheenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUser");

                    b.Navigation("Product");

                    b.Navigation("Sheen");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserDetail", b =>
                {
                    b.HasOne("FMFlow.Entities.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingID");

                    b.HasOne("FMFlow.Entities.FMTimeZone", "FMTimeZone")
                        .WithMany()
                        .HasForeignKey("FMTimeZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FlowUser", "FlowUser")
                        .WithOne("ProUser")
                        .HasForeignKey("FMFlow.Entities.ProUserDetail", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("FMTimeZone");

                    b.Navigation("FlowUser");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserFile", b =>
                {
                    b.HasOne("FMFlow.Entities.FileItem", "File")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.FileItem", "ThumbnailFile")
                        .WithMany()
                        .HasForeignKey("ThumbnailFileID");

                    b.HasOne("FMFlow.Entities.FlowUser", "FlowUser")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("FlowUser");

                    b.Navigation("ThumbnailFile");
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserToProZipcode", b =>
                {
                    b.HasOne("FMFlow.Entities.ProUserDetail", "ProUserDetail")
                        .WithMany("ProUserToProZipcodes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.ZipCode", "ProZipcode")
                        .WithMany()
                        .HasForeignKey("Zipcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUserDetail");

                    b.Navigation("ProZipcode");
                });

            modelBuilder.Entity("FMFlow.Entities.ProWeekDayAvailability", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany("ProWeekDayAvailabilities")
                        .HasForeignKey("ProUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUser");
                });

            modelBuilder.Entity("FMFlow.Entities.Product", b =>
                {
                    b.HasOne("FMFlow.Entities.FileItem", "PictureFile")
                        .WithMany()
                        .HasForeignKey("PictureFileId");

                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserId");

                    b.Navigation("PictureFile");

                    b.Navigation("ProUser");
                });

            modelBuilder.Entity("FMFlow.Entities.Project", b =>
                {
                    b.HasOne("FMFlow.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Lead");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("FMFlow.Entities.ProjectNote", b =>
                {
                    b.HasOne("FMFlow.Entities.ProUserDetail", "Pro")
                        .WithMany()
                        .HasForeignKey("ProId");

                    b.HasOne("FMFlow.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pro");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FMFlow.Entities.RequestedEstimate", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserID");

                    b.HasOne("FMFlow.Entities.Project", "Project")
                        .WithMany("RequestedEstimates")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FMFlow.Entities.ScheduledEstimate", b =>
                {
                    b.HasOne("FMFlow.Entities.FlowUser", "ProUser")
                        .WithMany()
                        .HasForeignKey("ProUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMFlow.Entities.Project", "Project")
                        .WithMany("ScheduledEstimates")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FMFlow.Entities.Transaction", b =>
                {
                    b.HasOne("FMFlow.Entities.Estimate", "Estimate")
                        .WithMany()
                        .HasForeignKey("EstimateId");

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("FMFlow.Entities.ZipCode", b =>
                {
                    b.HasOne("FMFlow.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateAbbreviation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("FMFlow.Entities.FlowUser", b =>
                {
                    b.Navigation("EmployeeUser");

                    b.Navigation("ProUser");

                    b.Navigation("ProWeekDayAvailabilities");
                });

            modelBuilder.Entity("FMFlow.Entities.Job", b =>
                {
                    b.Navigation("Estimate")
                        .IsRequired();
                });

            modelBuilder.Entity("FMFlow.Entities.ProUserDetail", b =>
                {
                    b.Navigation("ProUserToProZipcodes");
                });

            modelBuilder.Entity("FMFlow.Entities.Product", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("PaintSheens");
                });

            modelBuilder.Entity("FMFlow.Entities.Project", b =>
                {
                    b.Navigation("RequestedEstimates");

                    b.Navigation("ScheduledEstimates");
                });

            modelBuilder.Entity("FMFlow.Entities.RequestedEstimate", b =>
                {
                    b.Navigation("Estimates");
                });

            modelBuilder.Entity("FMFlow.Entities.ScheduledEstimate", b =>
                {
                    b.Navigation("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
