namespace FMFlow.ProUser.Interface;

public record SearchedProUserDetails(
	int UserID,
	string FirstName,
	string LastName,
	string Email,
	string PhoneNumber,
	string BusinessType,
	string TaxID,
	string NumberOfEmployees,
	string?[]? SizeOfJob,
	string?[]? Services,
	string? AddressOfStore,
	string? CityOfStore,
	string? StateOfStore,
	string? ZipCodeOfStore,
	string? BusinessName,
	string? BusinessAddress,
	string? City,
	string? State,
	string? ZipCode,
	bool IsApproved,
	bool? RequestedReferrals,
	string? Description,
	string? GoogleReview,
	string? YelpReview,
	string? OnboardingFormStop,
	DateTimeOffset? InsuranceExpDate,
	DateTimeOffset DateCreated,
	DateTimeOffset? DateUpdated,
	bool IsDeleted,
	DateTimeOffset? DateDeleted
);
